<script lang="ts">
  import { resolve } from '$app/paths';
  import type { IContestReport } from '$lib/server/report_types';
  import Report from '$lib/components/Report.svelte';

  interface Props {
    data: import('./$types').PageData;
  }

  let { data } = $props();
  let report: IContestReport = data.report;
  let path: string = data.path;
</script>

<svelte:head>
  <title
    >approval.vote: {report.info.jurisdictionName} / {report.info.name} / {report.info.date.slice(
      0,
      4
    )}</title
  >

  <!-- X (Twitter) Card Tags -->
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:site" content="@felixsargent" />
  <meta name="twitter:creator" content="@felixsargent" />
  <meta name="twitter:title" content="{report.info.jurisdictionName} / {report.info.name}" />
  <meta
    name="twitter:description"
    content="Detailed approval voting election results for {report.info.jurisdictionName} {report
      .info.name} ({report.info.date.slice(0, 4)})"
  />
  <meta name="twitter:image" content="https://approval.vote/images/{path}.png" />
  <meta
    name="twitter:image:alt"
    content="Election results visualization showing approval voting outcomes"
  />

  <!-- Open Graph Tags (also used by X) -->
  <meta property="og:type" content="article" />
  <meta property="og:url" content="https://approval.vote/report/{path}" />
  <meta property="og:title" content="{report.info.jurisdictionName} / {report.info.name}" />
  <meta
    property="og:description"
    content="Detailed approval voting election results for {report.info.jurisdictionName} {report
      .info.name} ({report.info.date.slice(0, 4)})"
  />
  <meta property="og:image" content="https://approval.vote/images/{path}.png" />
</svelte:head>

<div class="wide container">
  <Report {report} />
  <hr />
  <div class="row">
    <p style="font-style: italic;">
      This report was generated by <a href="{resolve('/')}">approval.vote</a>
      and may be reproduced under
      <a href="https://creativecommons.org/licenses/by/2.0/">CC-BY</a>. Learn more
      <a href="{resolve('/about')}">about approval.vote</a>.
      <span style="margin-left: 1em;">
        <a href="{resolve(`/images/${path}.png`)}">View card image →</a>
      </span>
    </p>
  </div>
</div>

<a style="display:none;" href={resolve(`/card/${path}`)}>card</a>
