<script lang="ts">
  /** @type {import('./$types').PageData} */
  export let data
  let report: IContestReport = data.report;
  let path: string = data.path;
  import { base } from '$app/paths';
  import type { IContestReport } from "$lib/server/report_types";
  import Report from '$lib/components/Report.svelte';
</script>

<svelte:head>
  <title
    >approval.vote: {report.info.jurisdictionName} / {report.info.name} / {report.info.date.slice(
      0,
      4
    )}</title
  >

  <meta
    property="og:title"
    content="{report.info.jurisdictionName} / {report.info.name}"
  />
  <meta property="twitter:card" content="summary" />
  <meta property="twitter:creator" content="@felixsargent" />
  <meta
    property="twitter:title"
    content="{report.info.jurisdictionName} / {report.info.name}"
  />
  <meta name="twitter:description" content="approval.vote: {report.info.jurisdictionName} / {report.info.name} / {report.info.date.slice(
      0,
      4
    )}" />
    <meta name="twitter:image" content="{base}/icon.png" />
</svelte:head>

<div class="wide container">
  <Report {report} />
  <hr />
  <div class="row">
    <p style="font-style: italic;">
      This report was generated by <a href="{base}/"
        >approval.vote</a
      >
      and may be reproduced under
      <a href="https://creativecommons.org/licenses/by/2.0/">CC-BY</a>. Learn
      more <a href="{base}/about">about approval.vote</a>.
    </p>
  </div>
</div>

<a style="display:none;" href={base + '/card/' + path}>card</a>
