[project]
name = "st-louis-cvr"
version = "0.1.0"
description = "St. Louis Cast Vote Record parser"
requires-python = ">=3.8"
dependencies = ["lxml>=5.0.0", "click>=8.0.0", "tqdm>=4.65.0", "pandas>=1.5.0"]

[project.scripts]
parse-cvr = "cvr_parser:main"
